// Flat ESLint config. Scope: server-side TypeScript only — `web/` has its
// own config that handles React-specific rules.
//
// We deliberately stay close to typescript-eslint's recommended set rather
// than crafting bespoke rules. The TypeScript compiler already enforces
// most invariants we care about (`strict`, `noUncheckedIndexedAccess`); the
// linter's job here is to catch the remaining sharp edges that tsc lets
// through — unused imports, accidental `any`, fall-through switches.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'web/**', // web/ has its own config
      'coverage/**',
      'src/db/migrations/meta/**', // generated by drizzle-kit
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      // Allow `void` to suppress floating-promise warnings without typing
      // `_ = await ...`. We use `void` intentionally in tests.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // The codebase already gates against `any` via `no-explicit-any`-style
      // discipline; downgrade to warn so existing pragmatic uses don't block CI.
      '@typescript-eslint/no-explicit-any': 'warn',
      // Tests reach into private state via `as any` casts in a few places;
      // tolerate that locally rather than scattering eslint-disable comments.
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  {
    // Tests have looser conventions (assertion patterns, fixture casts).
    files: ['tests/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
);
