import type { ScanJobResult } from './scanJob.js';

/**
 * In-memory cache of the most recent scan result. The mover/quarantine route
 * uses this to look up the planned actions for a given scanRunId.
 *
 * Persistence model: the actions themselves are NOT stored here long-term;
 * they're regenerated by re-scanning if needed. A scan + quarantine flow that
 * crosses a server restart simply re-scans first.
 */
const cache = new Map<number, ScanJobResult>();

export function rememberScan(result: ScanJobResult): void {
  cache.set(result.runId, result);
}

export function getScanResult(runId: number): ScanJobResult | null {
  return cache.get(runId) ?? null;
}

export function clearScanResults(): void {
  cache.clear();
}
